name: Build and Test

on:
  pull_request:
    branches:
      - '**/master'
      - master
  push:
    branches:
      - '**/master'
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install ncurses
      run: sudo apt-get install -y libncurses5 libncurses5-dev
    - name: make
      run: make
    - name: make test
      run: make test
