name: Build and Test

on:
  pull_request:
    branches:
      - '**/master'
      - master
  push:
    branches:
      - '**/master'
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      uses: ryankurte/action-apt@v0.1.0
      with:
        packages: libncurses5 libncurses5-dev
    - name: make
      run: make
    - name: make test
      run: make test
