name: Build and Test

on:
  pull_request:
    branches:
      - '**/master'
      - master
  push:
    branches:
      - '**/master'
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Package
      uses: mstksg/get-package@v1
      with:
        apt-get: libncurses5 libncurses5-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make test
      run: make test
